  // File: src/app/models/match.model.ts
  export interface Match {
    id?: string;          // Auto-generated by Firestore
    date: string;         // ISO date string of the match
    teams: {              // Array of teams
      player1: string;    // Player 1's name
      player2: string;    // Player 2's name
      score: string;      // Match score (e.g., "6-4")
    }[];
  }